# Codemagic – same as terminal: flutter build apk/appbundle --release
# Repo = this Flutter app only. First step writes android/local.properties so Gradle finds Flutter.

workflows:
  android-workflow:
    name: Android Build
    max_build_duration: 60
    environment:
      flutter: stable
    scripts:
      - name: Set Flutter path for Gradle
        script: |
          cd "$CM_BUILD_DIR"
          FLUTTER_SDK="${FLUTTER_ROOT:-$(cd "$(dirname "$(which flutter)")/.." && pwd)}"
          echo "flutter.sdk=$FLUTTER_SDK" > android/local.properties
      - name: Get packages and build
        script: |
          cd "$CM_BUILD_DIR"
          flutter pub get
          flutter build apk --release
          flutter build appbundle --release
    artifacts:
      - build/app/outputs/flutter-apk/*.apk
      - build/app/outputs/bundle/release/*.aab
    publishing:
      scripts:
        - name: Done
          script: echo "APK in Artifacts tab."
