# Codemagic – same as terminal: flutter build apk --release
# Repo = this Flutter app only. Android uses FLUTTER_ROOT when local.properties is missing.

workflows:
  android-workflow:
    name: Android Build
    max_build_duration: 60
    environment:
      flutter: stable
    scripts:
      - name: Get packages and build APK
        script: |
          cd "$CM_BUILD_DIR"
          flutter pub get
          flutter build apk --release
    artifacts:
      - build/app/outputs/flutter-apk/*.apk
    publishing:
      scripts:
        - name: Done
          script: echo "APK in Artifacts tab."
